#!/bin/bash

# Clonix: clonix
#
# Runner script for non-NixOS setups
# See main.py for arguments

echo "Initializing..."

if [[ ! -e .venv ]]; then
  echo "Creating virtual environment..."
  python3 -m venv .venv
fi

source .venv/bin/activate

pip -r ./requirements.txt install

python3 ./main.py $@
